### ISSUE TITLE
add new folder not showing text input for folder name

### ISSUE THREAD

**Issue by karlpatrickespiritu** [saadq/Materialize#81] opened 2016-11-22 11:59 UTC
### Theme Issue:

1. OS: Windowsw 7
2. Sublime Text version: v3 build 31 26
3. Materialize version: 2.6.2
4. Description of issue: add new folder not showing text input for folder name
5. Steps to reproduce (if appropriate): right click a folder in sidebar, then click `new folder` 
6. Screenshot of issue (if appropriate):

### Theme Request:

1. Theme Name:
2. Author Name:
3. Link to the color scheme:
4. License of color scheme:

**Comment by saadq** [comment] 2016-11-22 21:40
I think this is a duplicate of [51](https://github.com/saadq/Materialize/issues/51). Check out the [known issues](https://github.com/saadq/Materialize/#known-issues) that carried over from Material Theme. Basically, you just need to grab the border of the input panel and drag it, and it should fix the missing input field.

Please reopen this issue if there's still anything wrong! :)

**Closed by saadq** 2016-11-22 21:40 UTC

**Comment by karlpatrickespiritu** [comment] 2016-11-23 01:30
thanks! 👍
