### ISSUE TITLE
SCSS highlighting is not correct

### ISSUE THREAD

**Issue by kumarharsh** [saadq/Materialize#10] opened 2015-08-21 08:25 UTC
There is an SCSS package (https://packagecontrol.io/packages/SCSS), which does a much better job of highlighting SCSS files, which is severely lacking in the SCSS syntax highlight file bundled with Materialize.

Some of the things which are not highlighted by the bundled file:
* Comments
![comments](http://i.imgur.com/TDjRP8p.png)

* Variables
![vars](http://i.imgur.com/Y3urtZF.png)

* @include mixins
![mixins](http://i.imgur.com/KLayGNj.png)

* even the `&` parent selector
![& selector](http://i.imgur.com/ujIncEk.png)

These things are much better supported by the SCSS package. The problem is that this bundled scss package is overriding the standalone one whenever I load a scss file. Even setting the *Open all with the current extension as...* to the standalone SCSS doesn't help.

Can these bundled packages be removed? or somehow disabled?

**Comment by saadq** [comment] 2015-08-21 15:14
Hey kumarharsh,

Let me start off by saying I'm not too familiar with SCSS. With that said, did this problem only start happening when you installed Materialize? There is no bundled SCSS package with the theme, so it shouldn't have affected your syntax highlighting definition. It would help if you could do the following so I can replicate your issue and see what the desired result should be:

* Copy/paste your code into a comment here so I can try it out in my editor
* Post a screenshot of what the syntax highlighting **should** look like with the name of the color scheme you are using.
* Post a screenshot of what the syntax highlighting currently looks like with the name of the color scheme you are using.

**Comment by saadq** [comment] 2015-08-21 16:09
Hey @kumarharsh,

I reread your post and deleted my old reply. I think I may have a fix for this, I'm going to try some stuff out when I get home from work.

**Comment by JimmyRittenborg** [comment] 2015-08-21 16:19
I've been fideling round for some hours with this too (as i'm a complete ST noob) -it seems that this theme simply prevents me from using my installed sass and scss syntaxes anymore, driving me a bit nuts. But great to see that the issue at least has been raised in here :grin:

**Comment by saadq** [comment] 2015-08-21 16:22
Sorry for the inconvenience guys. The issue is coming from the [Langs](https://github.com/saadq/Materialize/tree/master/Langs) folder I have in this theme that helps me associate the file type icons for different languages. I will most likely have to remove the Sass and SCSS .`tmLanguage` files and try to get the file type icons working in a different way for them. Hopefully I can get this fixed by today.

**Comment by JimmyRittenborg** [comment] 2015-08-21 16:53
Oooh i see -that makes sense :+1: 

By the way, i really really love doing my work in this theme, especially because of the filetype icons :smiley: 

- Thanks

**Comment by saadq** [comment] 2015-08-22 00:28
Hey @kumarharsh  and @JimmyRittenborg. Your themes should have automatically updated. If they haven't please uninstall Materialize and reinstall it. Please check to see if Sass/SCSS are working fine now.

**Comment by saadq** [comment] 2015-08-22 02:39
@kumarharsh I also found another issue that was exclusive to Material Spacegray for SCSS/Sass. I've pushed the fix for it, and your theme should update automatically sometime soon. That should fix your issues.

**Comment by saadq** [comment] 2015-08-23 18:37
The issue should have been fixed. I'm going to assume that from the lack of response that there is no longer any problems. Please comment/reopen the issue if there are further issues.

**Closed by saadq** 2015-08-23 18:37 UTC

**Comment by JimmyRittenborg** [comment] 2015-08-23 18:39
Yeah, things seems to work great now, thanks :ok_hand:

**Comment by JimmyRittenborg** [comment] 2015-08-23 18:42
By the way, is this exclusive to me, or everyone -when i want to rename a file by right clicking on it in the sidebar, or if i want to create a new folder - that input field i completely hidden for some reason, seems to be an UI issue.

**Comment by saadq** [comment] 2015-08-23 18:57
Read the [known issues](https://github.com/saadq/Materialize#known-issues) at the bottom of the README. You basically just need to grab the top border of the input box and move it around. This is an issue that came from the original Material theme that you can ready about [here](https://github.com/equinusocio/material-theme/issues/67).

**Comment by JimmyRittenborg** [comment] 2015-08-23 18:59
Aaargh sorry, didn't see that - it works like a charm, thanks man! :v:

**Comment by saadq** [comment] 2015-08-23 19:01
Glad it worked :)

**Comment by RegisBiron** [comment] 2016-05-19 20:41
I'm still having syntax highlighting issues even after reinstalling ST 3, deleting all packages, reinstalling etc, clearing caches. My theme was perfect before I upgraded to stable 3114. 

These issues didn't exist in the previous stable build...

I've tried the above comments as well and nothing else seems to work.

I tried the Sublime SCSS package and it is still not like it used to be. My JSON highlighting is showing multiple colors depending on the nesting. 

## SASS 
![screen shot 2016-05-19 at 3 00 45 pm](https://cloud.githubusercontent.com/assets/8062034/15406039/a94b0f24-1dd2-11e6-85bd-eebee9b5744c.png)

## PostCSS using syntax highlighting for PostCSS package
![screen shot 2016-05-19 at 3 04 32 pm](https://cloud.githubusercontent.com/assets/8062034/15406128/1508256c-1dd3-11e6-8f04-13e47e255321.png)

## JSON
![screen shot 2016-05-19 at 3 02 33 pm](https://cloud.githubusercontent.com/assets/8062034/15406056/c2486e5e-1dd2-11e6-9fe1-515f06fd3edd.png)

### $ used in PHP and JS variables 
![screen shot 2016-05-19 at 3 03 15 pm](https://cloud.githubusercontent.com/assets/8062034/15406081/e5823d6e-1dd2-11e6-883a-8a6b6a3621ce.png)
